name: B2B CA3S DEV ENVIRONMENT DEPLOYMENT 
on:
  workflow-dispatch:
  schedule: 
    - cron: '1/5 * * * *'
jobs:
  deploy-images:
    name: Deploying to the Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Action Repo Checkout
      uses: actions/checkout@v2
      with:
        path: boc_github_workflows_test/actions


   
    - name: AWS CA3S DEV ECR CONFIGURE
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.RND_AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RND_AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RND_REGION }}
    
    - name: AWS CA3S DEV ECR LOGIN
      id: aws-dev-ecr-login
      uses: aws-actions/amazon-ecr-login@v1
 
    
    - name: Apply Env File
      id: vars
      run: |
        pwd
        ls -trl
        chmod 777 variable.env
        ./variable.env


    - name: Set up Reg URLs
      id: img-regs
      run: |
              echo "::set-output name=AWS_SOURCE_REG_URL::${{ steps.aws-dev-ecr-login.outputs.registry }}"
              echo "::set-output name=AWS_SOURCE_REPO_PREFIX::${{ steps.vars.outputs.AWS_REPO_PREFIX }}"
          
    - name: Details
      run: |
        aws ecr describe-repositories
      shell: bash

   deploy-images1:
      name: Deploy to environment
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Action Repo Checkout
        uses: actions/checkout@v2
        with:
          path: boc_github_workflows_test/actions

      - name: Image Verification Process
        uses: ./boc_github_workflows_test/actions/image-deployment/actions/imagevalidation
        with: 
          tag: 10.12.0
          component: webmethods-b2b
          source_aws_registry: ${{ steps.img-regs.outputs.AWS_SOURCE_REG_URL }}
          source_aws_repo_prefix: ${{ steps.img-regs.outputs.AWS_SOURCE_REPO_PREFIX }}
    
      - name: AWS credentials For common S3 Bucket
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RND_AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RND_AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RND_REGION }}
      

      - name: Deployement Process
        uses: ./boc_github_workflows_test/actions/image-deployment/actions/deploy-image
        with: 
          target_env: dev
          platform: aws
          tag: 10.12.0
          component: webmethods-b2b
          bucket_name: ${{ secrets.STABLE_BUILDS_BUCKET_NAME }}
          metadata_path: ${{ secrets.STABLE_BUILDS_METADATA_PATH }}
          app_version: 1012
          scripts: ./boc_github_workflows_test/actions/image-deployment/actions/deploy-image/dep.sh
      
      
