name: AWS CA3S DEV ENVIRONMENT DEPLOYMENT 
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 
  
jobs:
  configure-env:
    name: Configuring to CA3S Dev Environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Action Repo Checkout
      uses: actions/checkout@v2
      with:
        path: boc_github_workflows_test/actions
   
    - name: AWS CA3S DEV ECR CONFIGURE
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.RND_AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RND_AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RND_REGION }}
    
    - name: AWS CA3S DEV ECR LOGIN
      id: aws-dev-ecr-login
      uses: aws-actions/amazon-ecr-login@v1
 
    
    - name: Apply Env File
      id: vars
      run: |
        pwd
        ls -trl
        chmod 777 variable.env
        ./variable.env


    - name: Set up Reg URLs
      id: img-regs
      run: |
              echo "::set-output name=AWS_SOURCE_REG_URL::${{ steps.aws-dev-ecr-login.outputs.registry }}"
              echo "::set-output name=AWS_SOURCE_REPO_PREFIX::${{ steps.vars.outputs.AWS_REPO_PREFIX }}"
          
    - name: Details
      run: |
        aws ecr describe-repositories
      shell: bash
